# Generated by Django 5.2.1 on 2025-05-08 17:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.CharField(default='Unknown Agent', max_length=100)),
                ('customer', models.CharField(default='Unknown Customer', max_length=100)),
                ('duration', models.CharField(default='00:00', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('complete', 'Complete'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('compliance_status', models.CharField(choices=[('compliant', 'Compliant'), ('warning', 'Warning'), ('violation', 'Violation')], default='compliant', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CallAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_talk_time', models.IntegerField(default=0)),
                ('customer_talk_time', models.IntegerField(default=0)),
                ('agent_tone', models.FloatField(default=0.0)),
                ('customer_sentiment', models.FloatField(default=0.0)),
                ('silence_periods', models.IntegerField(default=0)),
                ('interruption_count', models.IntegerField(default=0)),
                ('key_phrases', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='analyzer.audiojob')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checklist', models.JSONField()),
                ('risk_level', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('score', models.IntegerField()),
                ('recommendations', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_report', to='analyzer.audiojob')),
            ],
        ),
        migrations.CreateModel(
            name='ContentSafety',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance', models.TextField()),
                ('category', models.CharField(max_length=50)),
                ('severity', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_safety', to='analyzer.audiojob')),
            ],
        ),
        migrations.CreateModel(
            name='Sentiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utterance', models.TextField()),
                ('sentiment', models.CharField(max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sentiments', to='analyzer.audiojob')),
            ],
        ),
        migrations.CreateModel(
            name='Transcript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speaker', models.CharField(choices=[('agent', 'Agent'), ('customer', 'Customer')], max_length=20)),
                ('start_time', models.CharField(max_length=20)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcripts', to='analyzer.audiojob')),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
    ]
