# Generated by Django 5.0.2 on 2025-05-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compliancereport',
            name='improvements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='compliancereport',
            name='violations',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='contentsafety',
            name='severity',
            field=models.IntegerField(),
        ),
    ]
