# Generated by Django 5.0.2 on 2025-05-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_compliancereport_improvements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiojob',
            name='current_step',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='audiojob',
            name='progress',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiojob',
            name='status_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
